#if !defined(OMC_SIM_SETTINGS_CMDLINE)
#define OMC_SIM_SETTINGS_CMDLINE
#define OMC_NUM_LINEAR_SYSTEMS 12
#define OMC_NUM_NONLINEAR_SYSTEMS 1
#define OMC_NUM_MIXED_SYSTEMS 0
#define OMC_NDELAY_EXPRESSIONS 0
#define OMC_NVAR_STRING 0
#define OMC_MODEL_PREFIX "Buildings_ThermalZones_ReducedOrder_Examples_SimpleRoomFourElements"
#define OMC_MINIMAL_RUNTIME 1
#define OMC_FMI_RUNTIME 1
#endif