/* Simulation code for Buildings.HeatTransfer.Windows.Examples.WindowCustomNoHeat generated by the OpenModelica Compiler OpenModelica 1.21.0~dev-298-g51286f2. */
#if !defined(Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat__MODEL_H)
#define Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "util/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functions.h"


extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_relationDescription(int i);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_initSample(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_linear_model_frame(void);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_linear_model_datarecovery_frame(void);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_mayer(DATA* data, modelica_real** res, short *);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_setInputData(DATA *data, const modelica_boolean file);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_inputNames(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_dataReconciliationInputNames(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Buildings_HeatTransfer_Windows_Examples_WindowCustomNoHeat__MODEL_H) */


