/* Simulation code for TwoWayValve generated by the OpenModelica Compiler v1.21.0-2-g0bc3d29bd9-cmake. */
#if !defined(TwoWayValve__MODEL_H)
#define TwoWayValve__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "TwoWayValve_functions.h"

#define Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow_index 0
#define Modelica_Fluid_Utilities_checkBoundary_index 1
#define Modelica_Utilities_Streams_error_index 2
#define TwoWayValve_sin_Medium_ThermodynamicState_index 3
#define TwoWayValve_sin_Medium_setState__pTX_index 4
#define TwoWayValve_sin_Medium_specificEnthalpy_index 5
#define TwoWayValve_sou_Medium_ThermodynamicState_index 6
#define TwoWayValve_sou_Medium_setState__pTX_index 7
#define TwoWayValve_sou_Medium_specificEnthalpy_index 8

extern void TwoWayValve_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void TwoWayValve_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void TwoWayValve_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int TwoWayValve_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int TwoWayValve_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int TwoWayValve_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TwoWayValve_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TwoWayValve_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int TwoWayValve_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int TwoWayValve_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int TwoWayValve_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int TwoWayValve_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int TwoWayValve_checkForAsserts(DATA *data, threadData_t *threadData);
extern int TwoWayValve_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int TwoWayValve_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int TwoWayValve_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* TwoWayValve_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* TwoWayValve_relationDescription(int i);
extern void TwoWayValve_function_initSample(DATA *data, threadData_t *threadData);
extern int TwoWayValve_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TwoWayValve_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TwoWayValve_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TwoWayValve_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TwoWayValve_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TwoWayValve_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TwoWayValve_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int TwoWayValve_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TwoWayValve_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TwoWayValve_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TwoWayValve_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TwoWayValve_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TwoWayValve_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int TwoWayValve_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* TwoWayValve_linear_model_frame(void);
extern const char* TwoWayValve_linear_model_datarecovery_frame(void);
extern int TwoWayValve_mayer(DATA* data, modelica_real** res, short *);
extern int TwoWayValve_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int TwoWayValve_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int TwoWayValve_setInputData(DATA *data, const modelica_boolean file);
extern int TwoWayValve_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void TwoWayValve_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void TwoWayValve_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int TwoWayValve_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void TwoWayValve_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void TwoWayValve_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int TwoWayValve_inputNames(DATA* data, char ** names);
extern int TwoWayValve_dataReconciliationInputNames(DATA* data, char ** names);
extern int TwoWayValve_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int TwoWayValve_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int TwoWayValve_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int TwoWayValve_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "TwoWayValve_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(TwoWayValve__MODEL_H) */


