# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=/usr/bin/cc
CXX=/usr/bin/c++
LINK=/usr/bin/cc -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC    
CPPFLAGS="-I/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/C-Sources" -I"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../include/omc/c" -I"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=TwoWayValve -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=2 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -lSimulationRuntimeC -lOpenModelicaRuntimeC -lomcgc -lzlib -llapack -lblas -lm -ldl -lpthread -lgfortran -lstdc++ -rdynamic 
LDFLAGS=-L"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc" -L"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib" -Wl,-rpath,"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/marius/Desktop/project1-boptest/testcases/singlezone_commercial_hydronic/models/OU44Emulator"
MAINFILE=TwoWayValve.c
MAINOBJ=TwoWayValve.o
CFILES=TwoWayValve_functions.c TwoWayValve_records.c \
TwoWayValve_01exo.c TwoWayValve_02nls.c TwoWayValve_03lsy.c TwoWayValve_04set.c TwoWayValve_05evt.c TwoWayValve_06inz.c TwoWayValve_07dly.c \
TwoWayValve_08bnd.c TwoWayValve_09alg.c TwoWayValve_10asr.c TwoWayValve_11mix.c TwoWayValve_12jac.c TwoWayValve_13opt.c TwoWayValve_14lnz.c \
TwoWayValve_15syn.c TwoWayValve_16dae.c TwoWayValve_17inl.c TwoWayValve_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) TwoWayValve.makefile TwoWayValve_literals.h TwoWayValve_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that TwoWayValve_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) TwoWayValve_functions.h TwoWayValve_literals.h $(OFILES)
	$(CC) -I. -o TwoWayValve$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-L/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc" "-L/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/" -Wl,-rpath="/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/" "-L/home/marius/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/marius/.openmodelica/binaries/Modelica" "-L/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/x86_64-linux" -Wl,-rpath="/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/x86_64-linux" "-L/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/linux64" -Wl,-rpath="/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/linux64" "-L/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library" -Wl,-rpath="/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f TwoWayValve_records.o $(MAINOBJ)

bundle:
	@tar -cvf TwoWayValve_Files.tar $(GENERATEDFILES)