#ifndef ThreeWayValveParameterization__H
#define ThreeWayValveParameterization__H
#include "meta/meta_modelica.h"
#include "util/modelica.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include "simulation/simulation_runtime.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  modelica_real _p;
  modelica_real _T;
} Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState__desc;

void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState__desc;

void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState__desc;

void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState), __VA_ARGS__)

DLLExport
modelica_real omc_Buildings_Fluid_Actuators_BaseClasses_equalPercentage(threadData_t *threadData, modelica_real _y, modelica_real _R, modelica_real _l, modelica_real _delta);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_BaseClasses_equalPercentage(threadData_t *threadData, modelica_metatype _y, modelica_metatype _R, modelica_metatype _l, modelica_metatype _delta);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_BaseClasses_equalPercentage,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_BaseClasses_equalPercentage,0}};
#define boxvar_Buildings_Fluid_Actuators_BaseClasses_equalPercentage MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_BaseClasses_equalPercentage)


DLLExport
Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_setState__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_setState__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_setState__pTX,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_setState__pTX,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_setState__pTX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_setState__pTX)


DLLExport
modelica_real omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_specificEnthalpy(threadData_t *threadData, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_specificEnthalpy(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_specificEnthalpy,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_specificEnthalpy,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_specificEnthalpy MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_specificEnthalpy)


DLLExport
Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_setState__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_setState__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_setState__pTX,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_setState__pTX,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_setState__pTX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_setState__pTX)


DLLExport
modelica_real omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_specificEnthalpy(threadData_t *threadData, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_specificEnthalpy(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_specificEnthalpy,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_specificEnthalpy,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_specificEnthalpy MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_specificEnthalpy)


DLLExport
Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_setState__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_setState__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_setState__pTX,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_setState__pTX,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_setState__pTX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_setState__pTX)


DLLExport
modelica_real omc_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_specificEnthalpy(threadData_t *threadData, Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_specificEnthalpy(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_specificEnthalpy,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_specificEnthalpy,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_specificEnthalpy MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_specificEnthalpy)


DLLExport
modelica_real omc_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp(threadData_t *threadData, modelica_real _dp, modelica_real _k, modelica_real _m_flow_turbulent);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp(threadData_t *threadData, modelica_metatype _dp, modelica_metatype _k, modelica_metatype _m_flow_turbulent);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp,2,0) {(void*) boxptr_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp,0}};
#define boxvar_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp)


DLLExport
void omc_Modelica_Fluid_Utilities_checkBoundary(threadData_t *threadData, modelica_string _mediumName, string_array _substanceNames, modelica_boolean _singleState, modelica_boolean _define_p, real_array _X_boundary, modelica_string _modelName);
DLLExport
void boxptr_Modelica_Fluid_Utilities_checkBoundary(threadData_t *threadData, modelica_metatype _mediumName, modelica_metatype _substanceNames, modelica_metatype _singleState, modelica_metatype _define_p, modelica_metatype _X_boundary, modelica_metatype _modelName);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_checkBoundary,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_checkBoundary,0}};
#define boxvar_Modelica_Fluid_Utilities_checkBoundary MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_checkBoundary)


DLLExport
void omc_Modelica_Utilities_Streams_error(threadData_t *threadData, modelica_string _string);
#define boxptr_Modelica_Utilities_Streams_error omc_Modelica_Utilities_Streams_error
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Utilities_Streams_error,2,0) {(void*) boxptr_Modelica_Utilities_Streams_error,0}};
#define boxvar_Modelica_Utilities_Streams_error MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Utilities_Streams_error)

/*
 * The function has annotation(Include=...>) or is builtin
 * the external function definition should be present
 * in one of these files and have this prototype:
 * extern void ModelicaError(const char* (*_string*));
 */
#include "ThreeWayValveParameterization_model.h"


#ifdef __cplusplus
}
#endif
#endif

