/* Simulation code for Buildings.Fluid.Actuators.Valves.Validation.ThreeWayValveParameterization generated by the OpenModelica Compiler v1.21.0-2-g0bc3d29bd9-cmake. */
#if !defined(ThreeWayValveParameterization__MODEL_H)
#define ThreeWayValveParameterization__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "ThreeWayValveParameterization_functions.h"

#define Buildings_Fluid_Actuators_BaseClasses_equalPercentage_index 0
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_ThermodynamicState_index 1
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_setState__pTX_index 2
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sin_Medium_specificEnthalpy_index 3
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_ThermodynamicState_index 4
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_setState__pTX_index 5
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou1_Medium_specificEnthalpy_index 6
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_ThermodynamicState_index 7
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_setState__pTX_index 8
#define Buildings_Fluid_Actuators_Valves_Validation_ThreeWayValveParameterization_sou3_Medium_specificEnthalpy_index 9
#define Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp_index 10
#define Modelica_Fluid_Utilities_checkBoundary_index 11
#define Modelica_Utilities_Streams_error_index 12

extern void ThreeWayValveParameterization_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void ThreeWayValveParameterization_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int ThreeWayValveParameterization_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_checkForAsserts(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int ThreeWayValveParameterization_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* ThreeWayValveParameterization_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* ThreeWayValveParameterization_relationDescription(int i);
extern void ThreeWayValveParameterization_function_initSample(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWayValveParameterization_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWayValveParameterization_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWayValveParameterization_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWayValveParameterization_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWayValveParameterization_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWayValveParameterization_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWayValveParameterization_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWayValveParameterization_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWayValveParameterization_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWayValveParameterization_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWayValveParameterization_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWayValveParameterization_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWayValveParameterization_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* ThreeWayValveParameterization_linear_model_frame(void);
extern const char* ThreeWayValveParameterization_linear_model_datarecovery_frame(void);
extern int ThreeWayValveParameterization_mayer(DATA* data, modelica_real** res, short *);
extern int ThreeWayValveParameterization_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int ThreeWayValveParameterization_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int ThreeWayValveParameterization_setInputData(DATA *data, const modelica_boolean file);
extern int ThreeWayValveParameterization_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void ThreeWayValveParameterization_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void ThreeWayValveParameterization_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int ThreeWayValveParameterization_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void ThreeWayValveParameterization_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void ThreeWayValveParameterization_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int ThreeWayValveParameterization_inputNames(DATA* data, char ** names);
extern int ThreeWayValveParameterization_dataReconciliationInputNames(DATA* data, char ** names);
extern int ThreeWayValveParameterization_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int ThreeWayValveParameterization_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int ThreeWayValveParameterization_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int ThreeWayValveParameterization_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "ThreeWayValveParameterization_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(ThreeWayValveParameterization__MODEL_H) */


