# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++ -std=c++14
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers -Wno-parentheses-equality ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I"/usr/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Simple2R2CSimple -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas  -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/marius/fmu_test/buildopt/test"
MAINFILE=Simple2R2CSimple.c
MAINOBJ=Simple2R2CSimple.o
CFILES=Simple2R2CSimple_functions.c Simple2R2CSimple_records.c \
Simple2R2CSimple_01exo.c Simple2R2CSimple_02nls.c Simple2R2CSimple_03lsy.c Simple2R2CSimple_04set.c Simple2R2CSimple_05evt.c Simple2R2CSimple_06inz.c Simple2R2CSimple_07dly.c \
Simple2R2CSimple_08bnd.c Simple2R2CSimple_09alg.c Simple2R2CSimple_10asr.c Simple2R2CSimple_11mix.c Simple2R2CSimple_12jac.c Simple2R2CSimple_13opt.c Simple2R2CSimple_14lnz.c \
Simple2R2CSimple_15syn.c Simple2R2CSimple_16dae.c Simple2R2CSimple_17inl.c Simple2R2CSimple_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) Simple2R2CSimple.makefile Simple2R2CSimple_literals.h Simple2R2CSimple_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that Simple2R2CSimple_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) Simple2R2CSimple_functions.h Simple2R2CSimple_literals.h $(OFILES)
	$(CC) -I. -o Simple2R2CSimple$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f Simple2R2CSimple_records.o $(MAINOBJ)

bundle:
	@tar -cvf Simple2R2CSimple_Files.tar $(GENERATEDFILES)