# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++ -std=c++14
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=-O0 -g
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers -Wno-parentheses-equality ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I"/usr/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=LimPID -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas  -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/marius/fmu_test/buildopt/test"
MAINFILE=LimPID.c
MAINOBJ=LimPID.o
CFILES=LimPID_functions.c LimPID_records.c \
LimPID_01exo.c LimPID_02nls.c LimPID_03lsy.c LimPID_04set.c LimPID_05evt.c LimPID_06inz.c LimPID_07dly.c \
LimPID_08bnd.c LimPID_09alg.c LimPID_10asr.c LimPID_11mix.c LimPID_12jac.c LimPID_13opt.c LimPID_14lnz.c \
LimPID_15syn.c LimPID_16dae.c LimPID_17inl.c LimPID_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) LimPID.makefile LimPID_literals.h LimPID_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that LimPID_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) LimPID_functions.h LimPID_literals.h $(OFILES)
	$(CC) -I. -o LimPID$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f LimPID_records.o $(MAINOBJ)

bundle:
	@tar -cvf LimPID_Files.tar $(GENERATEDFILES)