#ifdef OMC_BASE_FILE
  #define OMC_FILE OMC_BASE_FILE
#else
  #define OMC_FILE "/home/marius/LimPID/LimPID_model.h"
#endif
/* Simulation code for LimPID generated by the OpenModelica Compiler OpenModelica 1.21.0~dev-298-g51286f2. */
#if !defined(LimPID__MODEL_H)
#define LimPID__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "util/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "LimPID_functions.h"


extern void LimPID_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void LimPID_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int LimPID_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int LimPID_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int LimPID_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int LimPID_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int LimPID_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int LimPID_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int LimPID_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int LimPID_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int LimPID_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int LimPID_checkForAsserts(DATA *data, threadData_t *threadData);
extern int LimPID_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int LimPID_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int LimPID_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* LimPID_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* LimPID_relationDescription(int i);
extern void LimPID_function_initSample(DATA *data, threadData_t *threadData);
extern int LimPID_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LimPID_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LimPID_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LimPID_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LimPID_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LimPID_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LimPID_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LimPID_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LimPID_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LimPID_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LimPID_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LimPID_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LimPID_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LimPID_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* LimPID_linear_model_frame(void);
extern const char* LimPID_linear_model_datarecovery_frame(void);
extern int LimPID_mayer(DATA* data, modelica_real** res, short *);
extern int LimPID_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int LimPID_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int LimPID_setInputData(DATA *data, const modelica_boolean file);
extern int LimPID_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void LimPID_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void LimPID_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int LimPID_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void LimPID_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void LimPID_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int LimPID_inputNames(DATA* data, char ** names);
extern int LimPID_dataReconciliationInputNames(DATA* data, char ** names);
extern int LimPID_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int LimPID_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int LimPID_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int LimPID_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "LimPID_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(LimPID__MODEL_H) */


