/* Simulation code for Buildings.HeatTransfer.Windows.BaseClasses.Examples.DataTest generated by the OpenModelica Compiler OpenModelica 1.22.0~dev-17-g88d7b96. */
#if !defined(Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest__MODEL_H)
#define Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functions.h"

#define Buildings_HeatTransfer_Windows_Functions_devAbsExteriorIrradiationInteriorShading_index 0
#define Buildings_HeatTransfer_Windows_Functions_devAbsInteriorIrradiationInteriorShading_index 1
#define Buildings_HeatTransfer_Windows_Functions_getGlassTR_index 2
#define Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationExteriorShading_index 3
#define Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationInteriorShading_index 4
#define Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationNoShading_index 5
#define Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationExteriorShading_index 6
#define Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationInteriorShading_index 7
#define Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationNoShading_index 8
#define Buildings_HeatTransfer_Windows_Functions_glassProperty_index 9
#define Buildings_HeatTransfer_Windows_Functions_glassPropertyCoated_index 10
#define Buildings_HeatTransfer_Windows_Functions_glassPropertyUncoated_index 11
#define Buildings_HeatTransfer_Windows_Functions_glassTRExteriorIrradiationNoShading_index 12
#define Buildings_HeatTransfer_Windows_Functions_glassTRInteriorIrradiationNoShading_index 13
#define Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiationInteriorShading_index 14
#define Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiatrionExteriorShading_index 15
#define Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationExteriorShading_index 16
#define Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationInteriorShading_index 17
#define Buildings_Utilities_Math_Functions_trapezoidalIntegration_index 18

extern void Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_relationDescription(int i);
extern void Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_initSample(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_linear_model_frame(void);
extern const char* Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_linear_model_datarecovery_frame(void);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_mayer(DATA* data, modelica_real** res, short *);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_setInputData(DATA *data, const modelica_boolean file);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_inputNames(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_dataReconciliationInputNames(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest__MODEL_H) */


