/* Additional record code for Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest generated by the OpenModelica Compiler OpenModelica 1.22.0~dev-17-g88d7b96. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

