#ifndef Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest__H
#define Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest__H
#include "meta/meta_modelica.h"
#include "util/modelica.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include "simulation/simulation_runtime.h"
#ifdef __cplusplus
extern "C" {
#endif


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_devAbsExteriorIrradiationInteriorShading(threadData_t *threadData, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_devAbsExteriorIrradiationInteriorShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_devAbsExteriorIrradiationInteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_devAbsExteriorIrradiationInteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_devAbsExteriorIrradiationInteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_devAbsExteriorIrradiationInteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_devAbsInteriorIrradiationInteriorShading(threadData_t *threadData, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_devAbsInteriorIrradiationInteriorShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_devAbsInteriorIrradiationInteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_devAbsInteriorIrradiationInteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_devAbsInteriorIrradiationInteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_devAbsInteriorIrradiationInteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_getGlassTR(threadData_t *threadData, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM, real_array _layer);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_getGlassTR(threadData_t *threadData, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM, modelica_metatype _layer);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_getGlassTR,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_getGlassTR,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_getGlassTR MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_getGlassTR)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationExteriorShading(threadData_t *threadData, real_array _absExtIrrNoSha, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationExteriorShading(threadData_t *threadData, modelica_metatype _absExtIrrNoSha, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationExteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationExteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationExteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationExteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationInteriorShading(threadData_t *threadData, real_array _absExtIrrNoSha, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationInteriorShading(threadData_t *threadData, modelica_metatype _absExtIrrNoSha, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationInteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationInteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationInteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationInteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationNoShading(threadData_t *threadData, real_array _traRef, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationNoShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationNoShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationNoShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationNoShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsExteriorIrradiationNoShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationExteriorShading(threadData_t *threadData, real_array _absIntIrrNoSha, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationExteriorShading(threadData_t *threadData, modelica_metatype _absIntIrrNoSha, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationExteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationExteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationExteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationExteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationInteriorShading(threadData_t *threadData, real_array _absIntIrrNoSha, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationInteriorShading(threadData_t *threadData, modelica_metatype _absIntIrrNoSha, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationInteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationInteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationInteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationInteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationNoShading(threadData_t *threadData, real_array _traRef, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationNoShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationNoShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationNoShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationNoShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassAbsInteriorIrradiationNoShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassProperty(threadData_t *threadData, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM, real_array _glass, real_array _xGla, real_array _psi);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassProperty(threadData_t *threadData, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM, modelica_metatype _glass, modelica_metatype _xGla, modelica_metatype _psi);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassProperty,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassProperty,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassProperty MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassProperty)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassPropertyCoated(threadData_t *threadData, modelica_integer _HEM, real_array _glass, real_array _psi);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassPropertyCoated(threadData_t *threadData, modelica_metatype _HEM, modelica_metatype _glass, modelica_metatype _psi);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassPropertyCoated,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassPropertyCoated,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassPropertyCoated MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassPropertyCoated)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassPropertyUncoated(threadData_t *threadData, modelica_integer _HEM, real_array _glass, modelica_real _x, real_array _psi);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassPropertyUncoated(threadData_t *threadData, modelica_metatype _HEM, modelica_metatype _glass, modelica_metatype _x, modelica_metatype _psi);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassPropertyUncoated,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassPropertyUncoated,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassPropertyUncoated MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassPropertyUncoated)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassTRExteriorIrradiationNoShading(threadData_t *threadData, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM, real_array _layer);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassTRExteriorIrradiationNoShading(threadData_t *threadData, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM, modelica_metatype _layer);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassTRExteriorIrradiationNoShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassTRExteriorIrradiationNoShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassTRExteriorIrradiationNoShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassTRExteriorIrradiationNoShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_glassTRInteriorIrradiationNoShading(threadData_t *threadData, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM, real_array _layer);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_glassTRInteriorIrradiationNoShading(threadData_t *threadData, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM, modelica_metatype _layer);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassTRInteriorIrradiationNoShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_glassTRInteriorIrradiationNoShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_glassTRInteriorIrradiationNoShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_glassTRInteriorIrradiationNoShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiationInteriorShading(threadData_t *threadData, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiationInteriorShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiationInteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiationInteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiationInteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiationInteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiatrionExteriorShading(threadData_t *threadData, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiatrionExteriorShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiatrionExteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiatrionExteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiatrionExteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTExteriorIrradiatrionExteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationExteriorShading(threadData_t *threadData, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationExteriorShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationExteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationExteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationExteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationExteriorShading)


DLLExport
real_array omc_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationInteriorShading(threadData_t *threadData, real_array _traRef, real_array _traRefShaDev, modelica_integer _N, modelica_integer _NSta, modelica_integer _HEM);
DLLExport
modelica_metatype boxptr_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationInteriorShading(threadData_t *threadData, modelica_metatype _traRef, modelica_metatype _traRefShaDev, modelica_metatype _N, modelica_metatype _NSta, modelica_metatype _HEM);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationInteriorShading,2,0) {(void*) boxptr_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationInteriorShading,0}};
#define boxvar_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationInteriorShading MMC_REFSTRUCTLIT(boxvar_lit_Buildings_HeatTransfer_Windows_Functions_winTRInteriorIrradiationInteriorShading)


DLLExport
modelica_real omc_Buildings_Utilities_Math_Functions_trapezoidalIntegration(threadData_t *threadData, modelica_integer _N, real_array _f, modelica_real _deltaX);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_trapezoidalIntegration(threadData_t *threadData, modelica_metatype _N, modelica_metatype _f, modelica_metatype _deltaX);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_trapezoidalIntegration,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_trapezoidalIntegration,0}};
#define boxvar_Buildings_Utilities_Math_Functions_trapezoidalIntegration MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_trapezoidalIntegration)
#include "Buildings_HeatTransfer_Windows_BaseClasses_Examples_DataTest_model.h"


#ifdef __cplusplus
}
#endif
#endif

