/* Simulation code for Pade generated by the OpenModelica Compiler v1.21.0-2-g0bc3d29bd9-cmake. */
#if !defined(Pade__MODEL_H)
#define Pade__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Pade_functions.h"


extern void Pade_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Pade_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Pade_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Pade_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Pade_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Pade_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Pade_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Pade_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Pade_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Pade_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Pade_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Pade_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Pade_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Pade_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Pade_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Pade_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Pade_relationDescription(int i);
extern void Pade_function_initSample(DATA *data, threadData_t *threadData);
extern int Pade_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Pade_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Pade_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Pade_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Pade_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Pade_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Pade_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Pade_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Pade_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Pade_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Pade_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Pade_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Pade_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Pade_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Pade_linear_model_frame(void);
extern const char* Pade_linear_model_datarecovery_frame(void);
extern int Pade_mayer(DATA* data, modelica_real** res, short *);
extern int Pade_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Pade_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Pade_setInputData(DATA *data, const modelica_boolean file);
extern int Pade_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Pade_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Pade_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Pade_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Pade_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Pade_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Pade_inputNames(DATA* data, char ** names);
extern int Pade_dataReconciliationInputNames(DATA* data, char ** names);
extern int Pade_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int Pade_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Pade_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Pade_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Pade_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Pade__MODEL_H) */


