/* Simulation code for Buildings.HeatTransfer.Windows.Examples.WindowCustom generated by the OpenModelica Compiler OpenModelica 1.21.0~dev-298-g51286f2. */
#if !defined(Buildings_HeatTransfer_Windows_Examples_WindowCustom__MODEL_H)
#define Buildings_HeatTransfer_Windows_Examples_WindowCustom__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "util/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Buildings_HeatTransfer_Windows_Examples_WindowCustom_functions.h"


extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustom_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustom_relationDescription(int i);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_initSample(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustom_linear_model_frame(void);
extern const char* Buildings_HeatTransfer_Windows_Examples_WindowCustom_linear_model_datarecovery_frame(void);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_mayer(DATA* data, modelica_real** res, short *);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_setInputData(DATA *data, const modelica_boolean file);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Buildings_HeatTransfer_Windows_Examples_WindowCustom_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_inputNames(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_dataReconciliationInputNames(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Buildings_HeatTransfer_Windows_Examples_WindowCustom_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Buildings_HeatTransfer_Windows_Examples_WindowCustom_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Buildings_HeatTransfer_Windows_Examples_WindowCustom__MODEL_H) */


