/* Simulation code for Simple2R2C_inputs generated by the OpenModelica Compiler v1.21.0-2-g0bc3d29bd9-cmake. */
#if !defined(Simple2R2C_inputs__MODEL_H)
#define Simple2R2C_inputs__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Simple2R2C_inputs_functions.h"


extern void Simple2R2C_inputs_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Simple2R2C_inputs_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Simple2R2C_inputs_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Simple2R2C_inputs_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Simple2R2C_inputs_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Simple2R2C_inputs_relationDescription(int i);
extern void Simple2R2C_inputs_function_initSample(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple2R2C_inputs_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple2R2C_inputs_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple2R2C_inputs_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple2R2C_inputs_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple2R2C_inputs_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple2R2C_inputs_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple2R2C_inputs_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple2R2C_inputs_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple2R2C_inputs_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple2R2C_inputs_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple2R2C_inputs_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple2R2C_inputs_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple2R2C_inputs_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Simple2R2C_inputs_linear_model_frame(void);
extern const char* Simple2R2C_inputs_linear_model_datarecovery_frame(void);
extern int Simple2R2C_inputs_mayer(DATA* data, modelica_real** res, short *);
extern int Simple2R2C_inputs_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Simple2R2C_inputs_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Simple2R2C_inputs_setInputData(DATA *data, const modelica_boolean file);
extern int Simple2R2C_inputs_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Simple2R2C_inputs_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Simple2R2C_inputs_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Simple2R2C_inputs_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Simple2R2C_inputs_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Simple2R2C_inputs_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Simple2R2C_inputs_inputNames(DATA* data, char ** names);
extern int Simple2R2C_inputs_dataReconciliationInputNames(DATA* data, char ** names);
extern int Simple2R2C_inputs_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int Simple2R2C_inputs_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Simple2R2C_inputs_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Simple2R2C_inputs_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Simple2R2C_inputs_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Simple2R2C_inputs__MODEL_H) */


