# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=/usr/bin/cc
CXX=/usr/bin/c++
LINK=/usr/bin/cc -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC    
CPPFLAGS="-I/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/C-Sources" -I"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../include/omc/c" -I"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=ThreeWayValves -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -lSimulationRuntimeC -lOpenModelicaRuntimeC -lomcgc -lzlib -llapack -lblas -lm -ldl -lpthread -lgfortran -lstdc++ -rdynamic 
LDFLAGS=-L"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc" -L"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib" -Wl,-rpath,"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/marius/.openmodelica/libraries/Buildings 10.0.0/Fluid/Actuators/Valves/Examples"
MAINFILE=ThreeWayValves.c
MAINOBJ=ThreeWayValves.o
CFILES=ThreeWayValves_functions.c ThreeWayValves_records.c \
ThreeWayValves_01exo.c ThreeWayValves_02nls.c ThreeWayValves_03lsy.c ThreeWayValves_04set.c ThreeWayValves_05evt.c ThreeWayValves_06inz.c ThreeWayValves_07dly.c \
ThreeWayValves_08bnd.c ThreeWayValves_09alg.c ThreeWayValves_10asr.c ThreeWayValves_11mix.c ThreeWayValves_12jac.c ThreeWayValves_13opt.c ThreeWayValves_14lnz.c \
ThreeWayValves_15syn.c ThreeWayValves_16dae.c ThreeWayValves_17inl.c ThreeWayValves_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) ThreeWayValves.makefile ThreeWayValves_literals.h ThreeWayValves_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that ThreeWayValves_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) ThreeWayValves_functions.h ThreeWayValves_literals.h $(OFILES)
	$(CC) -I. -o ThreeWayValves$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-L/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/x86_64-linux-gnu/omc" "-L/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/" -Wl,-rpath="/home/marius/Documents/OpenModelica/build/install_cmake/bin/../lib/" "-L/home/marius/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/marius/.openmodelica/binaries/Modelica" "-L/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/x86_64-linux" -Wl,-rpath="/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/x86_64-linux" "-L/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/linux64" -Wl,-rpath="/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/linux64" "-L/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library" -Wl,-rpath="/home/marius/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f ThreeWayValves_records.o $(MAINOBJ)

bundle:
	@tar -cvf ThreeWayValves_Files.tar $(GENERATEDFILES)