#ifndef ThreeWayValves__H
#define ThreeWayValves__H
#include "meta/meta_modelica.h"
#include "util/modelica.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include "simulation/simulation_runtime.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  modelica_real _p;
  modelica_real _T;
} Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState__desc;

void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState__desc;

void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState__desc;

void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState), __VA_ARGS__)

DLLExport
modelica_real omc__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fdp(threadData_t *threadData, modelica_real _dp, modelica_real _k, modelica_real _m_flow_turbulent, modelica_real __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fdp_24funDERdp, modelica_real __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fdp_24funDERk, modelica_real __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fdp_24funDERm_5Fflow_5Fturbulent);
DLLExport
modelica_metatype boxptr__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fdp(threadData_t *threadData, modelica_metatype _dp, modelica_metatype _k, modelica_metatype _m_flow_turbulent, modelica_metatype __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fdp_24funDERdp, modelica_metatype __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fdp_24funDERk, modelica_metatype __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fdp_24funDERm_5Fflow_5Fturbulent);
static const MMC_DEFSTRUCTLIT(boxvar_lit__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fdp,2,0) {(void*) boxptr__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fdp,0}};
#define boxvar__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fdp MMC_REFSTRUCTLIT(boxvar_lit__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fdp)


DLLExport
modelica_real omc_Buildings_Fluid_Actuators_BaseClasses_equalPercentage(threadData_t *threadData, modelica_real _y, modelica_real _R, modelica_real _l, modelica_real _delta);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_BaseClasses_equalPercentage(threadData_t *threadData, modelica_metatype _y, modelica_metatype _R, modelica_metatype _l, modelica_metatype _delta);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_BaseClasses_equalPercentage,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_BaseClasses_equalPercentage,0}};
#define boxvar_Buildings_Fluid_Actuators_BaseClasses_equalPercentage MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_BaseClasses_equalPercentage)


DLLExport
Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_ret_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sin_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState omc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_sou_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valEquPerLin_vol_Medium_temperature__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valEquPerLin_vol_Medium_temperature__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valEquPerLin_vol_Medium_temperature__phX,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valEquPerLin_vol_Medium_temperature__phX,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valEquPerLin_vol_Medium_temperature__phX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valEquPerLin_vol_Medium_temperature__phX)


DLLExport
modelica_real omc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valLin_vol_Medium_temperature__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valLin_vol_Medium_temperature__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valLin_vol_Medium_temperature__phX,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valLin_vol_Medium_temperature__phX,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valLin_vol_Medium_temperature__phX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valLin_vol_Medium_temperature__phX)


DLLExport
modelica_real omc_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valTab_vol_Medium_temperature__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valTab_vol_Medium_temperature__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valTab_vol_Medium_temperature__phX,2,0) {(void*) boxptr_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valTab_vol_Medium_temperature__phX,0}};
#define boxvar_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valTab_vol_Medium_temperature__phX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Actuators_Valves_Examples_ThreeWayValves_valTab_vol_Medium_temperature__phX)


DLLExport
modelica_real omc_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp(threadData_t *threadData, modelica_real _dp, modelica_real _k, modelica_real _m_flow_turbulent);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp(threadData_t *threadData, modelica_metatype _dp, modelica_metatype _k, modelica_metatype _m_flow_turbulent);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp,2,0) {(void*) boxptr_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp,0}};
#define boxvar_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__dp)


DLLExport
modelica_real omc_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax(threadData_t *threadData, modelica_complex _tableID);
DLLExport
modelica_metatype boxptr_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax(threadData_t *threadData, modelica_metatype _tableID);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax,2,0) {(void*) boxptr_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax,0}};
#define boxvar_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax)

extern double ModelicaStandardTables_CombiTable1D_maximumAbscissa(void * /*_tableID*/);


DLLExport
modelica_real omc_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin(threadData_t *threadData, modelica_complex _tableID);
DLLExport
modelica_metatype boxptr_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin(threadData_t *threadData, modelica_metatype _tableID);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin,2,0) {(void*) boxptr_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin,0}};
#define boxvar_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin)

extern double ModelicaStandardTables_CombiTable1D_minimumAbscissa(void * /*_tableID*/);


DLLExport
modelica_real omc_Modelica_Blocks_Tables_Internal_getTable1DValue(threadData_t *threadData, modelica_complex _tableID, modelica_integer _icol, modelica_real _u);
DLLExport
modelica_metatype boxptr_Modelica_Blocks_Tables_Internal_getTable1DValue(threadData_t *threadData, modelica_metatype _tableID, modelica_metatype _icol, modelica_metatype _u);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Tables_Internal_getTable1DValue,2,0) {(void*) boxptr_Modelica_Blocks_Tables_Internal_getTable1DValue,0}};
#define boxvar_Modelica_Blocks_Tables_Internal_getTable1DValue MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Tables_Internal_getTable1DValue)

extern double ModelicaStandardTables_CombiTable1D_getValue(void * /*_tableID*/, int /*_icol*/, double /*_u*/);


DLLExport
modelica_complex omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData_t *threadData, modelica_string _tableName, modelica_string _fileName, real_array _table, integer_array _columns, modelica_integer _smoothness, modelica_integer _extrapolation, modelica_boolean _verboseRead);
DLLExport
modelica_metatype boxptr_Modelica_Blocks_Types_ExternalCombiTable1D_constructor(threadData_t *threadData, modelica_metatype _tableName, modelica_metatype _fileName, modelica_metatype _table, modelica_metatype _columns, modelica_metatype _smoothness, modelica_metatype _extrapolation, modelica_metatype _verboseRead);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Types_ExternalCombiTable1D_constructor,2,0) {(void*) boxptr_Modelica_Blocks_Types_ExternalCombiTable1D_constructor,0}};
#define boxvar_Modelica_Blocks_Types_ExternalCombiTable1D_constructor MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Types_ExternalCombiTable1D_constructor)

extern void * ModelicaStandardTables_CombiTable1D_init2(const char* /*_fileName*/, const char* /*_tableName*/, const double* /*_table*/, size_t, size_t, const int* /*_columns*/, size_t, int /*_smoothness*/, int /*_extrapolation*/, int /*_verboseRead*/);


DLLExport
void omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData_t *threadData, modelica_complex _externalCombiTable1D);
DLLExport
void boxptr_Modelica_Blocks_Types_ExternalCombiTable1D_destructor(threadData_t *threadData, modelica_metatype _externalCombiTable1D);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Types_ExternalCombiTable1D_destructor,2,0) {(void*) boxptr_Modelica_Blocks_Types_ExternalCombiTable1D_destructor,0}};
#define boxvar_Modelica_Blocks_Types_ExternalCombiTable1D_destructor MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Blocks_Types_ExternalCombiTable1D_destructor)

extern void ModelicaStandardTables_CombiTable1D_close(void * /*_externalCombiTable1D*/);


DLLExport
void omc_Modelica_Fluid_Utilities_checkBoundary(threadData_t *threadData, modelica_string _mediumName, string_array _substanceNames, modelica_boolean _singleState, modelica_boolean _define_p, real_array _X_boundary, modelica_string _modelName);
DLLExport
void boxptr_Modelica_Fluid_Utilities_checkBoundary(threadData_t *threadData, modelica_metatype _mediumName, modelica_metatype _substanceNames, modelica_metatype _singleState, modelica_metatype _define_p, modelica_metatype _X_boundary, modelica_metatype _modelName);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_checkBoundary,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_checkBoundary,0}};
#define boxvar_Modelica_Fluid_Utilities_checkBoundary MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_checkBoundary)


DLLExport
void omc_Modelica_Utilities_Streams_error(threadData_t *threadData, modelica_string _string);
#define boxptr_Modelica_Utilities_Streams_error omc_Modelica_Utilities_Streams_error
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Utilities_Streams_error,2,0) {(void*) boxptr_Modelica_Utilities_Streams_error,0}};
#define boxvar_Modelica_Utilities_Streams_error MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Utilities_Streams_error)

/*
 * The function has annotation(Include=...>) or is builtin
 * the external function definition should be present
 * in one of these files and have this prototype:
 * extern void ModelicaError(const char* (*_string*));
 */
#include "ThreeWayValves_model.h"


#ifdef __cplusplus
}
#endif
#endif

