#pragma once

/*****************************************************************************
*
* Simulation code for FunctionCall functions generated by the OpenModelica Compiler.
*
*****************************************************************************/

class Functions
{
public:
  Functions(double& simTime, bool& initial, bool& terminate);
  ~Functions();
  //Modelica functions
  
  void Assert(bool cond, string msg);
  
  //Literals
private:
  //Function return variables
  double& _simTime;
  bool& _terminate;
  bool& _initial;
  /*extraFuncs*/
};