/* Additional record code for Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit generated by the OpenModelica Compiler OpenModelica 1.21.0~dev-298-g51286f2. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.bou.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc_added 1
const char* Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc__fields[3] = {"n","V_flow","dp"};
struct record_description Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc = {
  "Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal", /* package_record__X */
  "Buildings.Fluid.Movers.BaseClasses.Characteristics.flowParametersInternal", /* package.record_X */
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc__fields
};

void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* ths = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_ths);
  // ths->_n has no default value.
  alloc_real_array(&(ths->_V_flow), 1, (_index_t)ths->_n); // ths->_V_flow has no default value.
  alloc_real_array(&(ths->_dp), 1, (_index_t)ths->_n); // ths->_dp has no default value.
}
void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_integer in_n, real_array in_V_flow, real_array in_dp) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* dst = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_dst);
  dst->_n = in_n;
  dst->_V_flow = in_V_flow;
  dst->_dp = in_dp;
}

void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* src = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_src);
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* dst = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_dst);
  dst->_n = src->_n;
  real_array_copy_data(src->_V_flow, dst->_V_flow);
  real_array_copy_data(src->_dp, dst->_dp);
}


#define Buildings_Fluid_Movers_BaseClasses_Euler_peak__desc_added 1
const char* Buildings_Fluid_Movers_BaseClasses_Euler_peak__desc__fields[3] = {"V_flow","dp","eta"};
struct record_description Buildings_Fluid_Movers_BaseClasses_Euler_peak__desc = {
  "Buildings_Fluid_Movers_BaseClasses_Euler_peak", /* package_record__X */
  "Buildings.Fluid.Movers.BaseClasses.Euler.peak", /* package.record_X */
  Buildings_Fluid_Movers_BaseClasses_Euler_peak__desc__fields
};

void Buildings_Fluid_Movers_BaseClasses_Euler_peak_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_Movers_BaseClasses_Euler_peak* ths = (Buildings_Fluid_Movers_BaseClasses_Euler_peak*)(v_ths);
  // ths->_V_flow has no default value.
  // ths->_dp has no default value.
  ths->_eta = 0.7;
}
void Buildings_Fluid_Movers_BaseClasses_Euler_peak_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_V_flow, modelica_real in_dp, modelica_real in_eta) {
  Buildings_Fluid_Movers_BaseClasses_Euler_peak* dst = (Buildings_Fluid_Movers_BaseClasses_Euler_peak*)(v_dst);
  dst->_V_flow = in_V_flow;
  dst->_dp = in_dp;
  dst->_eta = in_eta;
}

void Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_Movers_BaseClasses_Euler_peak* src = (Buildings_Fluid_Movers_BaseClasses_Euler_peak*)(v_src);
  Buildings_Fluid_Movers_BaseClasses_Euler_peak* dst = (Buildings_Fluid_Movers_BaseClasses_Euler_peak*)(v_dst);
  dst->_V_flow = src->_V_flow;
  dst->_dp = src->_dp;
  dst->_eta = src->_eta;
}


#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc_added 1
const char* Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc__fields[3] = {"V_flow","P","d"};
struct record_description Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc = {
  "Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative", /* package_record__X */
  "Buildings.Fluid.Movers.BaseClasses.Euler.powerWithDerivative", /* package.record_X */
  Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc__fields
};

void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* ths = (Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_ths);
  alloc_real_array(&(ths->_V_flow), 1, (_index_t)11); // ths->_V_flow has no default value.
  alloc_real_array(&(ths->_P), 1, (_index_t)11); // ths->_P has no default value.
  alloc_real_array(&(ths->_d), 1, (_index_t)11); // ths->_d has no default value.
}
void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_wrap_vars_p(threadData_t *threadData, void* v_dst , real_array in_V_flow, real_array in_P, real_array in_d) {
  Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* dst = (Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_dst);
  dst->_V_flow = in_V_flow;
  dst->_P = in_P;
  dst->_d = in_d;
}

void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* src = (Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_src);
  Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* dst = (Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_dst);
  real_array_copy_data(src->_V_flow, dst->_V_flow);
  real_array_copy_data(src->_P, dst->_P);
  real_array_copy_data(src->_d, dst->_d);
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.fan.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.fan.preSou.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.fan.vol.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.fan.vol.steBal.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.hea.outCon.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.hea.preDro.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.hvacAda.bou.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.FMI.ExportContainers.Examples.FMUs.PumpCircuit.resSup.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState__desc__fields
};

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState* ths = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState* src = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState*)(v_src);
  Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState* dst = (Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_1_2_3_construct_p(threadData_t *threadData, void* v_ths , real_array in_V_flow, real_array in_P, real_array in_d) {
  Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative* ths = (Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(v_ths);
  alloc_real_array(&(ths->_V_flow), 1, (_index_t)11);
  real_array_copy_data(in_V_flow, ths->_V_flow);
  
  alloc_real_array(&(ths->_P), 1, (_index_t)11);
  real_array_copy_data(in_P, ths->_P);
  
  alloc_real_array(&(ths->_d), 1, (_index_t)11);
  real_array_copy_data(in_d, ths->_d);
  
}

#ifdef __cplusplus
}
#endif

