#ifndef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit__H
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit__H
#include "meta/meta_modelica.h"
#include "util/modelica.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include "simulation/simulation_runtime.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  modelica_real _p;
  modelica_real _T;
} Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState), __VA_ARGS__)

typedef struct {
  modelica_integer _n;
  real_array _V_flow;
  real_array _dp;
} Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal;
extern struct record_description Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc;

void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_construct(td, ths ) Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_construct_p(td, &ths )
void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy(src,dst) Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p(&src, &dst)


void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_integer in_n, real_array in_V_flow, real_array in_dp);
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_wrap_vars(td, dst , in_n, in_V_flow, in_dp) Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_wrap_vars_p(td, &dst , in_n, in_V_flow, in_dp)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_to_vars_p(void* v_src , modelica_integer* in_n, real_array* in_V_flow, real_array* in_dp);
// #define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_to_vars(src,...) Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_array;
#define alloc_Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_construct_p, ndims, sizeof(Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal), __VA_ARGS__)
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal))
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal))
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_array_get(src,ndims,...)   (*(Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(generic_array_get(&src, sizeof(Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal), __VA_ARGS__)))
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal), __VA_ARGS__)

typedef struct {
  modelica_real _V_flow;
  modelica_real _dp;
  modelica_real _eta;
} Buildings_Fluid_Movers_BaseClasses_Euler_peak;
extern struct record_description Buildings_Fluid_Movers_BaseClasses_Euler_peak__desc;

void Buildings_Fluid_Movers_BaseClasses_Euler_peak_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Movers_BaseClasses_Euler_peak_construct(td, ths ) Buildings_Fluid_Movers_BaseClasses_Euler_peak_construct_p(td, &ths )
void Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy(src,dst) Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_p(&src, &dst)


void Buildings_Fluid_Movers_BaseClasses_Euler_peak_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_V_flow, modelica_real in_dp, modelica_real in_eta);
#define Buildings_Fluid_Movers_BaseClasses_Euler_peak_wrap_vars(td, dst , in_V_flow, in_dp, in_eta) Buildings_Fluid_Movers_BaseClasses_Euler_peak_wrap_vars_p(td, &dst , in_V_flow, in_dp, in_eta)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_to_vars_p(void* v_src , modelica_real* in_V_flow, modelica_real* in_dp, modelica_real* in_eta);
// #define Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_to_vars(src,...) Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Movers_BaseClasses_Euler_peak_array;
#define alloc_Buildings_Fluid_Movers_BaseClasses_Euler_peak_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Movers_BaseClasses_Euler_peak_construct_p, ndims, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_peak), __VA_ARGS__)
#define Buildings_Fluid_Movers_BaseClasses_Euler_peak_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_peak))
#define Buildings_Fluid_Movers_BaseClasses_Euler_peak_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_peak))
#define Buildings_Fluid_Movers_BaseClasses_Euler_peak_array_get(src,ndims,...)   (*(Buildings_Fluid_Movers_BaseClasses_Euler_peak*)(generic_array_get(&src, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_peak), __VA_ARGS__)))
#define Buildings_Fluid_Movers_BaseClasses_Euler_peak_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Movers_BaseClasses_Euler_peak_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_peak), __VA_ARGS__)

typedef struct {
  real_array _V_flow;
  real_array _P;
  real_array _d;
} Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative;
extern struct record_description Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative__desc;

void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_construct(td, ths ) Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_construct_p(td, &ths )
void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy(src,dst) Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_p(&src, &dst)


void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_wrap_vars_p(threadData_t *threadData , void* v_dst , real_array in_V_flow, real_array in_P, real_array in_d);
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_wrap_vars(td, dst , in_V_flow, in_P, in_d) Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_wrap_vars_p(td, &dst , in_V_flow, in_P, in_d)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_to_vars_p(void* v_src , real_array* in_V_flow, real_array* in_P, real_array* in_d);
// #define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_to_vars(src,...) Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_array;
#define alloc_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_construct_p, ndims, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative), __VA_ARGS__)
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative))
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative))
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_array_get(src,ndims,...)   (*(Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative*)(generic_array_get(&src, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative), __VA_ARGS__)))
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_copy_p, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState), __VA_ARGS__)

typedef Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState;
extern struct record_description Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState__desc;

void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths );
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_construct(td, ths ) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_construct_p(td, &ths )
void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy(src,dst) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_p(&src, &dst)


void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData , void* v_dst , modelica_real in_p, modelica_real in_T);
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_wrap_vars(td, dst , in_p, in_T) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_wrap_vars_p(td, &dst , in_p, in_T)

// This function is not needed anymore. If you want to know how a record
// is 'assigned to' in simulation context see assignRhsExpToRecordCrefSimContext and
// splitRecordAssignmentToMemberAssignments (simCode). Basically the record is
// split up assignments generated for each member individually.
// void Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_to_vars_p(void* v_src , modelica_real* in_p, modelica_real* in_T);
// #define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_to_vars(src,...) Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_to_vars_p(&src, __VA_ARGS__)

typedef base_array_t Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_array;
#define alloc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_construct_p, ndims, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState), __VA_ARGS__)
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_array_copy_data(src,dst)   generic_array_copy_data(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_array_alloc_copy(src,dst)  generic_array_alloc_copy(src, &dst, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_array_get(src,ndims,...)   (*(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState*)(generic_array_get(&src, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState), __VA_ARGS__)))
#define Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_set(dst,val,...)           generic_array_set(&dst, &val, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState_copy_p, sizeof(Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState), __VA_ARGS__)

void Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_1_2_3_construct_p(threadData_t *threadData, void* v_ths , real_array in_V_flow, real_array in_P, real_array in_d);
#define Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_1_2_3_construct(td, ths , in_V_flow, in_P, in_d) Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_1_2_3_construct_p(td, &ths , in_V_flow, in_P, in_d)

#define alloc_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_1_2_3_array(dst,ndims,...) generic_array_create(NULL, dst, Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative_1_2_3_construct_p, ndims, sizeof(Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative), __VA_ARGS__)

DLLExport
modelica_real omc__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fm_5F_5Fflow(threadData_t *threadData, modelica_real _m_flow, modelica_real _k, modelica_real _m_flow_turbulent, modelica_real __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fm_5Fflow_24funDERm_5Fflow, modelica_real __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fm_5Fflow_24funDERk, modelica_real __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fm_5Fflow_24funDERm_5Fflow_5Fturbulent);
DLLExport
modelica_metatype boxptr__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fm_5F_5Fflow(threadData_t *threadData, modelica_metatype _m_flow, modelica_metatype _k, modelica_metatype _m_flow_turbulent, modelica_metatype __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fm_5Fflow_24funDERm_5Fflow, modelica_metatype __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fm_5Fflow_24funDERk, modelica_metatype __omcQ_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5Fm_5Fflow_24funDERm_5Fflow_5Fturbulent);
static const MMC_DEFSTRUCTLIT(boxvar_lit__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fm_5F_5Fflow,2,0) {(void*) boxptr__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fm_5F_5Fflow,0}};
#define boxvar__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fm_5F_5Fflow MMC_REFSTRUCTLIT(boxvar_lit__omcQ_24DER_24Buildings_24PFluid_24PBaseClasses_24PFlowModels_24PbasicFlowFunction_5F_5Fm_5F_5Fflow)


DLLExport
modelica_real omc_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow(threadData_t *threadData, modelica_real _m_flow, modelica_real _k, modelica_real _m_flow_turbulent);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow(threadData_t *threadData, modelica_metatype _m_flow, modelica_metatype _k, modelica_metatype _m_flow_turbulent);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow,2,0) {(void*) boxptr_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow,0}};
#define boxvar_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_setState__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_setState__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_setState__pTX,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_setState__pTX,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_setState__pTX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_setState__pTX)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_specificEnthalpy(threadData_t *threadData, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_specificEnthalpy(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_specificEnthalpy,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_specificEnthalpy,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_specificEnthalpy MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_bou_Medium_specificEnthalpy)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_Medium_ThermodynamicState)


DLLExport
modelica_string omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_eff_getArrayAsString(threadData_t *threadData, real_array _array, modelica_string _varName, modelica_integer _minimumLength, modelica_integer _significantDigits);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_eff_getArrayAsString(threadData_t *threadData, modelica_metatype _array, modelica_metatype _varName, modelica_metatype _minimumLength, modelica_metatype _significantDigits);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_eff_getArrayAsString,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_eff_getArrayAsString,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_eff_getArrayAsString MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_eff_getArrayAsString)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_density(threadData_t *threadData, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_density(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_density,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_density,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_density MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_density)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_setState__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_setState__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_setState__phX,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_setState__phX,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_setState__phX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_preSou_Medium_setState__phX)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_specificEnthalpy__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_specificEnthalpy__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_specificEnthalpy__pTX,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_specificEnthalpy__pTX,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_specificEnthalpy__pTX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_specificEnthalpy__pTX)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_temperature__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_temperature__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_temperature__phX,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_temperature__phX,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_temperature__phX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_Medium_temperature__phX)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_fan_vol_steBal_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_setState__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_setState__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_setState__pTX,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_setState__pTX,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_setState__pTX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_setState__pTX)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_specificEnthalpy(threadData_t *threadData, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_specificEnthalpy(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_specificEnthalpy,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_specificEnthalpy,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_specificEnthalpy MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_outCon_Medium_specificEnthalpy)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_dynamicViscosity(threadData_t *threadData, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_dynamicViscosity(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_dynamicViscosity,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_dynamicViscosity,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_dynamicViscosity MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hea_preDro_Medium_dynamicViscosity)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_setState__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_setState__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_setState__pTX,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_setState__pTX,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_setState__pTX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_setState__pTX)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_specificEnthalpy(threadData_t *threadData, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_specificEnthalpy(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_specificEnthalpy,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_specificEnthalpy,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_specificEnthalpy MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_bou_Medium_specificEnthalpy)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_con_Medium_temperature__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_con_Medium_temperature__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_con_Medium_temperature__phX,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_con_Medium_temperature__phX,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_con_Medium_temperature__phX MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_hvacAda_con_Medium_temperature__phX)


DLLExport
Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState (threadData_t *threadData, modelica_real omc_p, modelica_real omc_T);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_dynamicViscosity(threadData_t *threadData, Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_dynamicViscosity(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_dynamicViscosity,2,0) {(void*) boxptr_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_dynamicViscosity,0}};
#define boxvar_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_dynamicViscosity MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_resSup_Medium_dynamicViscosity)


DLLExport
Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal omc_Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal (threadData_t *threadData, modelica_integer omc_n, real_array omc_V_flow, real_array omc_dp);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal(threadData_t *threadData, modelica_metatype _n, modelica_metatype _V_flow, modelica_metatype _dp);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal,2,0) {(void*) boxptr_Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal,0}};
#define boxvar_Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal)


DLLExport
modelica_real omc_Buildings_Fluid_Movers_BaseClasses_Euler_correlation(threadData_t *threadData, modelica_real _x);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_correlation(threadData_t *threadData, modelica_metatype _x);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_correlation,2,0) {(void*) boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_correlation,0}};
#define boxvar_Buildings_Fluid_Movers_BaseClasses_Euler_correlation MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_correlation)


DLLExport
modelica_real omc_Buildings_Fluid_Movers_BaseClasses_Euler_efficiency(threadData_t *threadData, Buildings_Fluid_Movers_BaseClasses_Euler_peak _peak, modelica_real _dp, modelica_real _V_flow, modelica_real _V_flow_dp_small);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_efficiency(threadData_t *threadData, modelica_metatype _peak, modelica_metatype _dp, modelica_metatype _V_flow, modelica_metatype _V_flow_dp_small);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_efficiency,2,0) {(void*) boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_efficiency,0}};
#define boxvar_Buildings_Fluid_Movers_BaseClasses_Euler_efficiency MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_efficiency)


DLLExport
Buildings_Fluid_Movers_BaseClasses_Euler_peak omc_Buildings_Fluid_Movers_BaseClasses_Euler_peak (threadData_t *threadData, modelica_real omc_V_flow, modelica_real omc_dp, modelica_real omc_eta);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_peak(threadData_t *threadData, modelica_metatype _V_flow, modelica_metatype _dp, modelica_metatype _eta);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_peak,2,0) {(void*) boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_peak,0}};
#define boxvar_Buildings_Fluid_Movers_BaseClasses_Euler_peak MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_peak)


DLLExport
Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative omc_Buildings_Fluid_Movers_BaseClasses_Euler_power(threadData_t *threadData, Buildings_Fluid_Movers_BaseClasses_Euler_peak _peak, Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal _pressure);
DLLExport
modelica_metatype boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_power(threadData_t *threadData, modelica_metatype _peak, modelica_metatype _pressure);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_power,2,0) {(void*) boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_power,0}};
#define boxvar_Buildings_Fluid_Movers_BaseClasses_Euler_power MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_power)


DLLExport
Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative omc_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative (threadData_t *threadData, real_array omc_V_flow, real_array omc_P, real_array omc_d);

DLLExport
modelica_metatype boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative(threadData_t *threadData, modelica_metatype _V_flow, modelica_metatype _P, modelica_metatype _d);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative,2,0) {(void*) boxptr_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative,0}};
#define boxvar_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Fluid_Movers_BaseClasses_Euler_powerWithDerivative)


DLLExport
modelica_real omc_Buildings_Utilities_Math_Functions_cubicHermiteLinearExtrapolation(threadData_t *threadData, modelica_real _x, modelica_real _x1, modelica_real _x2, modelica_real _y1, modelica_real _y2, modelica_real _y1d, modelica_real _y2d);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_cubicHermiteLinearExtrapolation(threadData_t *threadData, modelica_metatype _x, modelica_metatype _x1, modelica_metatype _x2, modelica_metatype _y1, modelica_metatype _y2, modelica_metatype _y1d, modelica_metatype _y2d);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_cubicHermiteLinearExtrapolation,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_cubicHermiteLinearExtrapolation,0}};
#define boxvar_Buildings_Utilities_Math_Functions_cubicHermiteLinearExtrapolation MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_cubicHermiteLinearExtrapolation)


DLLExport
modelica_boolean omc_Buildings_Utilities_Math_Functions_isMonotonic(threadData_t *threadData, real_array _x, modelica_boolean _strict);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_isMonotonic(threadData_t *threadData, modelica_metatype _x, modelica_metatype _strict);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_isMonotonic,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_isMonotonic,0}};
#define boxvar_Buildings_Utilities_Math_Functions_isMonotonic MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_isMonotonic)


DLLExport
modelica_real omc_Buildings_Utilities_Math_Functions_regStep(threadData_t *threadData, modelica_real _x, modelica_real _y1, modelica_real _y2, modelica_real _x_small);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_regStep(threadData_t *threadData, modelica_metatype _x, modelica_metatype _y1, modelica_metatype _y2, modelica_metatype _x_small);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_regStep,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_regStep,0}};
#define boxvar_Buildings_Utilities_Math_Functions_regStep MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_regStep)


DLLExport
modelica_real omc_Buildings_Utilities_Math_Functions_smoothInterpolation(threadData_t *threadData, modelica_real _x, real_array _xSup, real_array _ySup, modelica_boolean _ensureMonotonicity);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_smoothInterpolation(threadData_t *threadData, modelica_metatype _x, modelica_metatype _xSup, modelica_metatype _ySup, modelica_metatype _ensureMonotonicity);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_smoothInterpolation,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_smoothInterpolation,0}};
#define boxvar_Buildings_Utilities_Math_Functions_smoothInterpolation MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_smoothInterpolation)


DLLExport
modelica_real omc_Buildings_Utilities_Math_Functions_smoothMax(threadData_t *threadData, modelica_real _x1, modelica_real _x2, modelica_real _deltaX);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_smoothMax(threadData_t *threadData, modelica_metatype _x1, modelica_metatype _x2, modelica_metatype _deltaX);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_smoothMax,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_smoothMax,0}};
#define boxvar_Buildings_Utilities_Math_Functions_smoothMax MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_smoothMax)


DLLExport
real_array omc_Buildings_Utilities_Math_Functions_splineDerivatives(threadData_t *threadData, real_array _x, real_array _y, modelica_boolean _ensureMonotonicity);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_splineDerivatives(threadData_t *threadData, modelica_metatype _x, modelica_metatype _y, modelica_metatype _ensureMonotonicity);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_splineDerivatives,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_splineDerivatives,0}};
#define boxvar_Buildings_Utilities_Math_Functions_splineDerivatives MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_splineDerivatives)


DLLExport
modelica_real omc_Buildings_Utilities_Math_Functions_BaseClasses_smoothTransition(threadData_t *threadData, modelica_real _x, modelica_real _delta, modelica_real _deltaInv, modelica_real _a, modelica_real _b, modelica_real _c, modelica_real _d, modelica_real _e, modelica_real _f);
DLLExport
modelica_metatype boxptr_Buildings_Utilities_Math_Functions_BaseClasses_smoothTransition(threadData_t *threadData, modelica_metatype _x, modelica_metatype _delta, modelica_metatype _deltaInv, modelica_metatype _a, modelica_metatype _b, modelica_metatype _c, modelica_metatype _d, modelica_metatype _e, modelica_metatype _f);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_BaseClasses_smoothTransition,2,0) {(void*) boxptr_Buildings_Utilities_Math_Functions_BaseClasses_smoothTransition,0}};
#define boxvar_Buildings_Utilities_Math_Functions_BaseClasses_smoothTransition MMC_REFSTRUCTLIT(boxvar_lit_Buildings_Utilities_Math_Functions_BaseClasses_smoothTransition)


DLLExport
void omc_Modelica_Fluid_Utilities_checkBoundary(threadData_t *threadData, modelica_string _mediumName, string_array _substanceNames, modelica_boolean _singleState, modelica_boolean _define_p, real_array _X_boundary, modelica_string _modelName);
DLLExport
void boxptr_Modelica_Fluid_Utilities_checkBoundary(threadData_t *threadData, modelica_metatype _mediumName, modelica_metatype _substanceNames, modelica_metatype _singleState, modelica_metatype _define_p, modelica_metatype _X_boundary, modelica_metatype _modelName);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_checkBoundary,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_checkBoundary,0}};
#define boxvar_Modelica_Fluid_Utilities_checkBoundary MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_checkBoundary)


DLLExport
modelica_real omc_Modelica_Fluid_Utilities_cubicHermite(threadData_t *threadData, modelica_real _x, modelica_real _x1, modelica_real _x2, modelica_real _y1, modelica_real _y2, modelica_real _y1d, modelica_real _y2d);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Utilities_cubicHermite(threadData_t *threadData, modelica_metatype _x, modelica_metatype _x1, modelica_metatype _x2, modelica_metatype _y1, modelica_metatype _y2, modelica_metatype _y1d, modelica_metatype _y2d);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_cubicHermite,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_cubicHermite,0}};
#define boxvar_Modelica_Fluid_Utilities_cubicHermite MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_cubicHermite)


DLLExport
modelica_real omc_Modelica_Fluid_Utilities_regStep(threadData_t *threadData, modelica_real _x, modelica_real _y1, modelica_real _y2, modelica_real _x_small);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Utilities_regStep(threadData_t *threadData, modelica_metatype _x, modelica_metatype _y1, modelica_metatype _y2, modelica_metatype _x_small);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regStep,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_regStep,0}};
#define boxvar_Modelica_Fluid_Utilities_regStep MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regStep)


DLLExport
void omc_Modelica_Utilities_Streams_error(threadData_t *threadData, modelica_string _string);
#define boxptr_Modelica_Utilities_Streams_error omc_Modelica_Utilities_Streams_error
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Utilities_Streams_error,2,0) {(void*) boxptr_Modelica_Utilities_Streams_error,0}};
#define boxvar_Modelica_Utilities_Streams_error MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Utilities_Streams_error)

/*
 * The function has annotation(Include=...>) or is builtin
 * the external function definition should be present
 * in one of these files and have this prototype:
 * extern void ModelicaError(const char* (*_string*));
 */
#include "Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_PumpCircuit_model.h"


#ifdef __cplusplus
}
#endif
#endif

