/* Additional record code for Buildings_HeatTransfer_Windows_Examples_WinRadCustomWea generated by the OpenModelica Compiler OpenModelica 1.21.0~dev-298-g51286f2. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Buildings_HeatTransfer_Windows_Examples_WinRadCustomWea_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

