# Makefile generated by OpenModelica for native and cross compilation
# How to cross compile:
#  - build OpenModelica (omc) from source code (see github.com/OpenModelica)
#  - install a cross compiler, e.g. apt-get install g++-mingw-w64-i686
#  - fix or work around capitalization of windows.h in MSL, see
#      https://trac.modelica.org/Modelica/ticket/1962
#  - add the target triplet, e.g. i686-w64-mingw32, to
#      OMCompiler/SimulationRuntime/cpp/Makefile
#  - rebuild omc to add the new platform
#  - invoke the omc commands
#      setCommandLineOptions("--simCodeTarget=Cpp");
#      buildModelFMU(MyModel, platforms={"i686-w64-mingw32"});
#  - alternatively call this Makefile with
#      make TARGET_TRIPLET=i686-w64-mingw32 -f LimPID_FMU.makefile

#TARGET_TRIPLET=
OMHOME=/home/marius/Documents/OpenModelica/build_cmake/install_cmake/bin/..
include $(OMHOME)/include/omc/cpp/ModelicaConfig_gcc.inc
include $(OMHOME)/include/omc/cpp/ModelicaLibraryConfig_gcc.inc

# simulations use -O0 by default; can be changed to e.g. -O2 or -Ofast
SIM_OPT_LEVEL=-O0

# native build or cross compilation
ifeq ($(TARGET_TRIPLET),)
  TRIPLET=x86_64-linux-gnu
  CC=/usr/bin/cc
  CXX=/usr/bin/c++
  ABI_CFLAG=
  DLLEXT=.so
  PLATFORM=linux64
else
  TRIPLET=$(TARGET_TRIPLET)
  CC=$(TRIPLET)-gcc
  CXX=$(TRIPLET)-g++
  ABI_CFLAG=-D_GLIBCXX_USE_CXX11_ABI=0
  DLLEXT=$(if $(findstring mingw,$(TRIPLET)),.dll,.so)
  WORDSIZE=$(if $(findstring x86_64,$(TRIPLET)),64,32)
  PLATFORM=$(if $(findstring darwin,$(TRIPLET)),darwin,$(if $(findstring mingw,$(TRIPLET)),win,linux))$(WORDSIZE)
endif

CFLAGS_BASED_ON_INIT_FILE=
FMU_CFLAGS=$(subst -DUSE_THREAD,,$(subst -O0,$(SIM_OPT_LEVEL),$(SYSTEM_CFLAGS))) $(ABI_CFLAG)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) -Winvalid-pch $(FMU_CFLAGS) -DFMU_BUILD -DRUNTIME_STATIC_LINKING -I"$(OMHOME)/include/omc/cpp" -I"$(UMFPACK_INCLUDE)" -I"$(SUNDIALS_INCLUDE)" -I"$(BOOST_INCLUDE)"  

ifeq ($(USE_LOGGER),ON)
  $(eval CFLAGS=$(CFLAGS) -DUSE_LOGGER)
endif

LDFLAGS=-L"$(OMHOME)/lib/$(TRIPLET)/omc/cpp"  -Wl,--no-undefined

CALCHELPERMAINFILE=OMCppLimPIDCalcHelperMain.cpp

# CVode can be used for Co-Simulation FMUs, Kinsol is available to handle non linear equation systems
OMCPP_SOLVER_LIBS=-lOMCppNewton_static -lOMCppDgesvSolver_static -lOMCppSolver_static
ifeq ($(USE_FMU_SUNDIALS),ON)
$(eval OMCPP_SOLVER_LIBS=$(OMCPP_SOLVER_LIBS) -lOMCppKinsol_static $(SUNDIALS_LIBRARIES))
$(eval CFLAGS=-DENABLE_SUNDIALS_STATIC $(CFLAGS))
endif

CPPFLAGS=$(CFLAGS)

BINARIES=LimPID$(DLLEXT)

OMCPP_LIBS=-lOMCppSystem_static -lOMCppMath_static -lOMCppFMU_static $(OMCPP_SOLVER_LIBS) -lOMCppExtensionUtilities_static
MODELICA_UTILITIES_LIB=-lOMCppModelicaUtilities_static
EXTRA_LIBS=-L"/home/marius/Desktop/OM_wdir" 
LIBS=$(EXTRA_LIBS) $(OMCPP_LIBS) $(MODELICA_UTILITIES_LIB) $(BASE_LIB)

# link with simple dgesv or full lapack
ifeq ($(USE_DGESV),ON)
  $(eval LIBS=$(LIBS) -lOMCppDgesv_static)
else
  $(eval LIBS=$(LIBS) -L$(LAPACK_LIBS) $(LAPACK_LIBRARIES))
  $(eval BINARIES=$(BINARIES) )
endif

# need boost system lib prior to C++11, forcing also dynamic libs
ifeq ($(findstring USE_CPP_03,$(CFLAGS)),USE_CPP_03)
  $(eval LIBS=$(LIBS) -L"$(BOOST_LIBS)" -l$(BOOST_SYSTEM_LIB))
  $(eval BINARIES=$(BINARIES) $(BOOST_LIBS)/lib$(BOOST_SYSTEM_LIB)$(DLLEXT) )
# link static libs to avoid dependencies; can't link all static under Linux
else ifeq ($(findstring gcc,$(CC)),gcc)
  $(eval LIBS=$(LIBS) $(if $(findstring linux,$(PLATFORM)),-static-libstdc++ -static-libgcc,-static))
else ifeq ($(findstring clang,$(CC)),clang)
  $(eval LIBS=$(LIBS) $(if $(findstring linux,$(PLATFORM)),-static-libstdc++ -static-libgcc,-static))
endif

CPPFILES=$(CALCHELPERMAINFILE)
OFILES=$(CPPFILES:.cpp=.o)

.PHONY: LimPID.fmu $(CPPFILES) clean

LimPID.fmu: $(OFILES)
	$(CXX) -shared -o LimPID$(DLLEXT) $(OFILES) $(LDFLAGS) $(LIBS)
	mkdir -p "binaries/$(PLATFORM)"
	mv $(BINARIES) "binaries/$(PLATFORM)/"
	rm -rf sources
	mkdir -p sources
	install -p OMCppLimPID*.h OMCppLimPID*.cpp LimPID_init.xml LimPID_FMU.makefile sources/
ifeq ($(USE_FMU_SUNDIALS),ON)
	rm -rf documentation
	mkdir -p "documentation"
	cp $(SUNDIALS_LIBRARIES_KINSOL) "binaries/$(PLATFORM)/"
	cp "$(OMHOME)/share/omc/runtime/cpp/licenses/sundials.license" "documentation/"
endif
	rm -f LimPID.fmu
ifeq ($(USE_FMU_SUNDIALS),ON)
	zip -r "LimPID.fmu" modelDescription.xml binaries sources documentation
	rm -rf documentation
else
	zip -r "LimPID.fmu" modelDescription.xml binaries sources
endif

clean:
	rm -f OMCppLimPID* LimPID_FMU.* LimPID.def LimPID.sh LimPID.bat LimPID.makefile LimPID_init.xml
	rm -rf modelDescription.xml binaries sources documentation

