/*****************************************************************************
*
* Helper file that includes all alg-loop files.
* This file is generated by the OpenModelica Compiler and produced to speed-up the compile time.
*
*****************************************************************************/
#include <Core/System/LinearAlgLoopDefaultImplementation.h>
#include <Core/System/NonLinearAlgLoopDefaultImplementation.h>
//jac files
//alg loop files
