#pragma once
#if defined(__TRICORE__) || defined(__vxworks)
  #define BOOST_EXTENSION_SYSTEM_DECL
  #define BOOST_EXTENSION_EVENTHANDLING_DECL
#endif


#include <Core/System/SystemDefaultImplementation.h>

//Forward declaration to speed-up the compilation process
class EventHandling;
class DiscreteEvents;

/*****************************************************************************
*
* Simulation code for LimPID generated by the OpenModelica Compiler.
* System class LimPID implements the Interface IMixedSystem
*
*****************************************************************************/

class LimPID: public SystemDefaultImplementation
{
public:

    LimPID(IGlobalSettings* globalSettings, shared_ptr<ISimObjects> simObjects );
    LimPID(LimPID &instance);
    
    virtual ~LimPID();
    
    /// Releases the Modelica System
    virtual void destroy();
    /// Provide number (dimension) of variables according to the index
    // Provide number (dimension) of right hand sides (equations and/or residuals)
    virtual int getDimRHS()const;
    
    virtual void setRealStartValue(double& var,double val);
    virtual void setBoolStartValue(bool& var,bool val);
    virtual void setIntStartValue(int& var,int val);
    virtual void setStringStartValue(string& var,string val);
    
    virtual void setNumPartitions(int numPartitions);
    virtual int getNumPartitions();
    virtual void setPartitionActivation(bool* partitions);
    virtual void getPartitionActivation(bool* partitions);
    virtual int getActivator(int state);
    
    //Resets all time events
    
    // Provide variables with given index to the system
    virtual void getNominalStates(double* z);
    
    // Update transfer behavior of the system of equations according to command given by solver
    virtual bool evaluateAll(const UPDATETYPE command = IContinuous::UNDEF_UPDATE);
    virtual void evaluateODE(const UPDATETYPE command = IContinuous::UNDEF_UPDATE);
    virtual void evaluateZeroFuncs(const UPDATETYPE command = IContinuous::UNDEF_UPDATE);
    virtual bool evaluateConditions(const UPDATETYPE command);
    
    // Provide the right hand side (according to the index)
    virtual void getRHS(double* f);
    
    //Provide number (dimension) of zero functions
    virtual int getDimZeroFunc();
    //Provide number (dimension) of zero functions
    virtual int getDimClock();
    //Provides current values of root/zero functions
    virtual void getZeroFunc(double* f);
    virtual void setConditions(bool* c);
    virtual void getConditions(bool* c);
    virtual void getClockConditions(bool* c);
    
    //Called to handle an event
    virtual void handleEvent(const bool* events);
    //Checks if a discrete variable has changed and triggers an event
    virtual bool checkForDiscreteEvents();
    virtual bool isStepEvent();
    //sets the terminal status
    virtual void setTerminal(bool);
    //returns the terminal status
    virtual bool terminal();
    
    
    
    // M is regular
    virtual bool isODE();
    // M is singular
    virtual bool isAlgebraic();
    
    virtual int getDimTimeEvent() const;
    virtual std::pair<double,double>* getTimeEventData() const;
    virtual double computeNextTimeEvents(double currTime);
    //initializes the definition of time event samplers (i.e. starttime and frequency)
    virtual void initTimeEventData();
    
    // System is able to provide the Jacobian symbolically
    virtual bool provideSymbolicJacobian();
    
    virtual void restoreOldValues();
    virtual void restoreNewValues();
    virtual bool stepCompleted(double time);
    virtual bool stepStarted(double time);
    
    
    /// Provide boolean variables
    virtual void getBoolean(bool* z);
    /// Provide integer variables
    virtual void getInteger(int* z);
    /// Provide real variables
    virtual void getReal(double* z);
    /// Provide real variables
    virtual void getString(std::string* z);
    /// Provide boolean variables
    virtual void setBoolean(const bool* z);
    /// Provide integer variables
    virtual void setInteger(const int* z);
    /// Provide real variables
    virtual void setReal(const double* z);
    /// Provide real variables
    virtual void setString(const std::string* z);
    virtual bool getCondition(unsigned int index);
    
    shared_ptr<IAlgLoopSolverFactory> getAlgLoopSolverFactory();
    
protected:
    //Methods:
    bool isConsistent();
    
    //Saves all variables before an event is handled, is needed for the pre, edge and change operator
    void saveAll();
    
    void initStateVars();
    void initDerivativeVars();
    void initAlgVars();
    void initDiscreteAlgVars();
    void initIntAlgVars();
    void initBoolAlgVars();
    void initStringAlgVars();
    void initParameterRealVars();
    void initParameterIntVars();
    void initParameterBoolVars();
    void initParameterStringVars();
    void initAliasRealVars();
    void initAliasIntVars();
    void initAliasBoolVars();
    void initAliasStringVars();
    
    void deleteObjects();
    
    //Variables:
    shared_ptr<EventHandling> _event_handling;
    shared_ptr<DiscreteEvents> _discrete_events;
    bool _state_var_reinitialized;
    
    //pointer to simVars-array to speedup simulation and compile time
    double* _pointerToRealVars;
    int* _pointerToIntVars;
    bool* _pointerToBoolVars;
    string* _pointerToStringVars;
    
    int _dimPartitions;
    bool* _partitionActivation;
    int* _stateActivator;
    
    /*state vars*/
    double& _PI_P_I_P_y_;
    /*derivative vars*/
    double& __omcQ_24DER_P_PI_P_I_P_y_;
    /*real algvars*/
    double& _PI_P_Dzero_P_y_;
    double& _PI_P_I_P_u_;
    double& _PI_P_I_P_y_reset_internal_;
    double& _PI_P_P_P_y_;
    double& _PI_P_addP_P_y_;
    double& _PI_P_addPID_P_y_;
    double& _PI_P_addSat_P_y_;
    double& _PI_P_controlError_;
    double& _PI_P_gainPID_P_y_;
    double& _PI_P_gainTrack_P_y_;
    double& _PI_P_y_reset_internal_;
    double& _Tmeas_;
    double& _Tset_;
    double& _u_val_;
    /*discrete algvars*/
    /*int algvars*/
    /*bool algvars*/
    bool& _PI_P_I_P_trigger_internal_;
    /*string algvars*/
    /*parameter real vars*/
    double& _PI_P_Dzero_P_k_;
    double& _PI_P_I_P_k_;
    double& _PI_P_I_P_y_reset_;
    double& _PI_P_I_P_y_start_;
    double& _PI_P_Nd_;
    double& _PI_P_Ni_;
    double& _PI_P_P_P_k_;
    double& _PI_P_Td_;
    double& _PI_P_Ti_;
    double& _PI_P_addI_P_k1_;
    double& _PI_P_addI_P_k2_;
    double& _PI_P_addI_P_k3_;
    double& _PI_P_addP_P_k1_;
    double& _PI_P_addP_P_k2_;
    double& _PI_P_addPID_P_k1_;
    double& _PI_P_addPID_P_k2_;
    double& _PI_P_addPID_P_k3_;
    double& _PI_P_addSat_P_k1_;
    double& _PI_P_addSat_P_k2_;
    double& _PI_P_gainPID_P_k_;
    double& _PI_P_gainTrack_P_k_;
    double& _PI_P_k_;
    double& _PI_P_limiter_P_uMax_;
    double& _PI_P_limiter_P_uMin_;
    double& _PI_P_revAct_;
    double& _PI_P_wd_;
    double& _PI_P_wp_;
    double& _PI_P_xd_start_;
    double& _PI_P_xi_start_;
    double& _PI_P_yMax_;
    double& _PI_P_yMin_;
    double& _PI_P_y_reset_;
    double& _PI_P_y_start_;
    double& _ki_;
    double& _kp_;
    /*parameter int vars*/
    int& _PI_P_I_P_initType_;
    int& _PI_P_I_P_reset_;
    int& _PI_P_controllerType_;
    int& _PI_P_initType_;
    int& _PI_P_reset_;
    /*parameter bool vars*/
    bool& _PI_P_limiter_P_limitsAtInit_;
    bool& _PI_P_limiter_P_strict_;
    bool& _PI_P_reverseActing_;
    bool& _PI_P_strict_;
    bool& _PI_P_with_D_;
    bool& _PI_P_with_I_;
    /*string parameter variables*/
    /*alias real vars*/
    double& __omcQ_24outputAlias_5Fu_5Fval_;
    double& _PI_P_P_P_u_;
    double& _PI_P_addI_P_u1_;
    double& _PI_P_addI_P_u2_;
    double& _PI_P_addI_P_u3_;
    double& _PI_P_addI_P_y_;
    double& _PI_P_addP_P_u1_;
    double& _PI_P_addP_P_u2_;
    double& _PI_P_addPID_P_u1_;
    double& _PI_P_addPID_P_u2_;
    double& _PI_P_addPID_P_u3_;
    double& _PI_P_addSat_P_u1_;
    double& _PI_P_addSat_P_u2_;
    double& _PI_P_gainPID_P_u_;
    double& _PI_P_gainTrack_P_u_;
    double& _PI_P_limiter_P_u_;
    double& _PI_P_limiter_P_y_;
    double& _PI_P_u_m_;
    double& _PI_P_u_s_;
    double& _PI_P_y_;
    /*alias int vars*/
    /*alias bool vars*/
    /*string alias variables*/
    /*external variables*/
    /*auxiliary DAE variables*/
    Functions* _functions;
    
    shared_ptr<IPropertyReader> _reader;
    shared_ptr<IAlgLoopSolverFactory> _algLoopSolverFactory;    ///< Factory that provides an appropriate solver



      
      
      


    
    /// Equations
    FORCE_INLINE void evaluate_16();
    FORCE_INLINE void evaluate_17();
    FORCE_INLINE void evaluate_18();
    FORCE_INLINE void evaluate_19();
    FORCE_INLINE void evaluate_20();
    FORCE_INLINE void evaluate_21();
    FORCE_INLINE void evaluate_22();
    FORCE_INLINE void evaluate_23();
    FORCE_INLINE void evaluate_24();
    FORCE_INLINE void evaluate_25();
    /// Clocked synchronous equations
    void evaluateClocked(int index);
    /*Additional member functions*/
    void evaluateAll_0(const UPDATETYPE command);
    void evaluateODE_0(const UPDATETYPE command);
    void initStateVars_0();
    void initDerivativeVars_0();
    void initAlgVars_0();
    void initBoolAlgVars_0();
    void initParameterRealVars_0();
    void initParameterIntVars_0();
    void initParameterBoolVars_0();
    void initAliasRealVars_0();
    void initConstVals();
};